# Generated by Django 3.1.4 on 2021-01-11 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_drive_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drive_ingredient',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
