# Generated by Django 3.1.4 on 2021-01-11 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_auto_20210111_2201'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='drive_ingredient',
            unique_together={('ingredient', 'drive')},
        ),
    ]
