# Generated by Django 3.1.4 on 2021-01-12 22:22

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_auto_20210111_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='drive',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drive_ingredient',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredient',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[("Entrées / Hors d'oeuvre", "Entrées / Hors d'oeuvre"), ('Soupes', 'Soupes'), ('Salades', 'Salades'), ('Plats principaux', 'Plats principaux'), ('Desserts', 'Desserts'), ('Collations', 'Collations'), ('Petits déjeuner', 'Petits déjeuner'), ('Sandwiches', 'Sandwiches'), ('Boîte à lunch (Panier repas)', 'Boîte à lunch (Panier repas)'), ('Sauces et trempettes', 'Sauces et trempettes'), ('Vinaigrettes', 'Vinaigrettes'), ('Boissons', 'Boissons')], max_length=100)),
                ('level', models.CharField(choices=[('Très facile', 'Très facile'), ('Facile', 'Facile'), ('Intermédiaire', 'Intermédiaire'), ('Master', 'Master')], max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('portion', models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')])),
                ('cooking_time', models.IntegerField(choices=[(0, 0), (5, 5), (10, 10), (15, 15), (20, 20), (25, 25), (30, 30), (35, 35), (40, 40), (45, 45), (50, 50), (55, 55), (60, 60)])),
                ('preparation', models.IntegerField(choices=[(0, 0), (5, 5), (10, 10), (15, 15), (20, 20), (25, 25), (30, 30)])),
                ('diet', models.CharField(choices=[('Hyperproteiné', 'Hyperproteiné'), ('Protéiné', 'Protéiné'), ('Dissocié', 'Hyperproteiné'), ('Hyperproteiné', 'Dissocié'), ('Anticellulite', 'Anticellulite'), ('Détox', 'Détox'), ('Sans sel', 'Sans sel'), ('Hypoglucidique', 'Hypoglucidique')], max_length=100)),
                ('is_feature', models.BooleanField(default=False)),
                ('description', ckeditor.fields.RichTextField()),
                ('recipe_photo', models.ImageField(upload_to='recipe/')),
                ('recipe_photo_1', models.ImageField(upload_to='recipe/')),
                ('recipe_photo_2', models.ImageField(upload_to='recipe/')),
                ('recipe_photo_3', models.ImageField(upload_to='recipe/')),
                ('recipe_photo_4', models.ImageField(upload_to='recipe/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('ingredients', models.ManyToManyField(to='recipe.Ingredient')),
            ],
        ),
    ]
