# Generated by Django 3.1.4 on 2021-01-12 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_auto_20210112_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='image',
            field=models.ImageField(upload_to='ingredient/'),
        ),
    ]
