# Generated by Django 3.1.4 on 2021-01-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_auto_20210114_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='diet',
            field=models.CharField(choices=[('Hyperproteiné', 'Hyperproteiné'), ('Protéiné', 'Protéiné'), ('Dissocié', 'Hyperproteiné'), ('Hyperproteiné', 'Dissocié'), ('Anticellulite', 'Anticellulite'), ('Détox', 'Détox'), ('Sans sel', 'Sans sel'), ('Hypoglucidique', 'Hypoglucidique'), ('Vegan', 'Vegan'), ('Végétarien', 'Végétarien'), ('Hallal', 'Hallal'), ('Sans gluten', 'Sans gluten'), ('Sans Lactose', 'Sans Lactose'), ('Casher', 'Casher')], max_length=100),
        ),
    ]
