# Generated by Django 3.1.4 on 2020-12-15 23:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
