# Generated by Django 3.1.4 on 2020-12-16 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20201216_2157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='designation',
            new_name='job_title',
        ),
    ]
